# Generated by Django 4.2.15 on 2024-11-04 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom_utilisateur', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('assure', 'Assuré'), ('employeur', 'Employeur'), ('admin', 'Administrateur')], max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_assure', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('etat_civil', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('date_affiliation', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_declaration', models.CharField(choices=[('Revenus', 'Déclaration de revenus'), ('Mariage', 'Déclaration de mariage'), ('Naissance', 'Déclaration de naissance'), ('Résidence', 'Changement de résidence')], max_length=50)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.assure')),
            ],
        ),
        migrations.CreateModel(
            name='DemandePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.assure')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLegislative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_annonce', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('réussie', 'Réussie'), ('échouée', 'Échouée')], default='en_attente', max_length=20)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_confirmation', models.TextField(blank=True, null=True)),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.assure')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_type', models.CharField(choices=[('prestation', 'Prestation'), ('declaration', 'Déclaration')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('approuve', 'Approuvé'), ('rejeté', 'Rejeté'), ('documents_manquants', 'Documents manquants')], default='en_attente', max_length=50)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.declaration')),
                ('demande_prestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.demandeprestation')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationPension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_depart_retraite', models.IntegerField()),
                ('salaire_moyen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_annees_contribution', models.IntegerField()),
                ('montant_pension_simulee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_simulation', models.DateTimeField(auto_now_add=True)),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.assure')),
            ],
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(choices=[('cotisation', 'Rappel de paiement de cotisation'), ('document', 'Rappel de soumission de document')], max_length=50)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('message', models.CharField(max_length=255)),
                ('est_envoye', models.BooleanField(default=False)),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.assure')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date_envoyee', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.assure')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('ip_adresse', models.GenericIPAddressField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('numero_identification', models.CharField(max_length=20, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('date_inscription', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DroitsAssure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_pension_estimee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('age_retraite_estime', models.IntegerField(default=60)),
                ('allocations_familiales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('autres_droits', models.TextField(blank=True, null=True)),
                ('assure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobile.assure')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/')),
                ('type_document', models.CharField(choices=[('Prestation', 'Document pour prestation'), ('Declaration', 'Document pour déclaration')], max_length=50)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.declaration')),
                ('demande_prestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.demandeprestation')),
            ],
        ),
        migrations.AddField(
            model_name='demandeprestation',
            name='type_prestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.typeprestation'),
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_annee', models.CharField(max_length=7)),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_cotisation_salariale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_cotisation_patronale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.assure')),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.employeur')),
            ],
        ),
    ]
